<Project Sdk="Microsoft.NET.Sdk.Razor">

	<ItemGroup>
		<PackageReference Include="bunit" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Oqtane.Shared" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Client\ICTAce.FileHub.Client.csproj" />
	</ItemGroup>

</Project>
